### ISSUE TITLE
.chucknorris or .chuck

### ISSUE THREAD

**Issue by Percussive-Maintenance** [deathbybandaid/sopel-modules#259]
A module that where the user could type .chucknorris and get a random chuck norrisism.  
Optional feature would be able to insert user: .chucknorris DoubleD would return something like "DoubleD threw a grenade and killed 50 people, then it exploded." by replacing the string "Chuck Norris" with username.
Possible website to pull from if able: http://chucknorrisjokes.linkpress.info/top-100

**Comment by Percussive-Maintenance** [comment]
import sopel.module
import requests
import json
import sys
import os
moduledir = os.path.dirname(__file__)
sys.path.append(moduledir)
from SpicebotShared import *

@sopel.module.commands('chucknorris','chuck')
def mainfunction(bot, trigger):
    enablestatus = spicebot_prerun(bot, trigger)
    if not enablestatus:
        execute_main(bot, trigger)
    
def execute_main(bot, trigger):
    joke = getJoke()
    if joke:
        if not trigger.group(2):
            bot.say(joke)
        elif not trigger.group(2).strip() == bot.nick:
            joke = joke.replace('Chuck Norris', trigger.group(2).strip())
            bot.say(joke)        
    else:
        bot.say('Chuck will find you.')

def getJoke():
    url = 'https://api.chucknorris.io/jokes/random'
    try:
      page = requests.get(url)
      result = page.content
      jsonjoke = json.loads(result)
      joke = jsonjoke['value']
    except:
      joke = "Chuck Norris broke the interwebs."
    return joke

**Comment by deathbybandaid** [comment]
done
