### ISSUE TITLE
FR: canifight everyone

### ISSUE THREAD

**Issue by Berserkir-Wolf** [deathbybandaid/sopel-modules#383]
.duel canifight allows checking individual people. 
.duel canifight errors. 

Suggest .duel canifight have 'if target=everyone' added to check full assault timeout.

**Comment by deathbybandaid** [comment]
good idea,,,

I'm looking at somehow combining canifight and whocanifight

maybe something like    .duel opponents   (whocanifight equivalent)

and then sub commands for other stuff

**Comment by Berserkir-Wolf** [comment]
.duel opponents for checking who it's on for
.duel opponent nick for checking individual
.duel assault to check if the assault can be used?

**Comment by deathbybandaid** [comment]
it's called warroom now
