### ISSUE TITLE
should .seen require spicebot opt-in

### ISSUE THREAD

**Issue by deathbybandaid** [deathbybandaid/sopel-modules#398]

**Comment by Percussive-Maintenance** [comment]
I think if they have spicebot on that counts as an opt-in.  It would be nice if some how this could .seen anyone (maybe other than admins) so it tags them.  makes them aware that something is happening in the group to come and join the conversation again.

**Comment by deathbybandaid** [comment]
the question is,,, should we track people that have not opted into spicebot?

additionally, should using this command require being opted in?

**Comment by Percussive-Maintenance** [comment]
Maybe change the process a little...
Once a month SpiceBot tags everyone inviting them to join in the chat conversation. (Possibly exclude ops?)
More often use a .seen on anyone with spicebot on

**Comment by Berserkir-Wolf** [comment]
I see no issue with it watching everyone who shows up. No different to a websites with analytics, which logs visit time/broswer/user agent/IP/time online...
Bot just logs Nick+last post.
