### ISSUE TITLE
freenode commands

### ISSUE THREAD

**Issue by deathbybandaid** [deathbybandaid/sopel-modules#399]
Occasionally, I see people forget to use a "/" in front of commands instead of a "."

should make a module that will do something like:

John Smith:     .msg nickserv
SpiceBot:         I think you meant to type /msg nickserv

Additioanlly if somebody runs   .ban   instead of   /ban   and they are not OP it should say something like

"You have no power here!"

**Comment by Percussive-Maintenance** [comment]
Done
