### ISSUE TITLE
One Casino class/file instead of many files

### ISSUE THREAD

**Issue by josh-cunning** [deathbybandaid/sopel-modules#438]
I am thinking it would be better to combine all the gambling like the lottery, blackjack, roulette, etc. into one module/set of commands.  It would be .gamble/casino followed by the type of game you want to play.
Most casino style games are pretty similar so it would save on writing a lot of code and might be easier for people to use. 
What do you think? 
Also I don't know if it would be possible to have one module accept and proccess multiple keywords.

**Comment by Berserkir-Wolf** [comment]
Yes please.
It'll make documentation cleaner as well.

There are a couple ways this could work.
If you want .casino spin and .casino roulette etc, you could reference duels for this (.duel 'option')
If you want separate commands you could reference [NukeIt](https://github.com/deathbybandaid/sopel-modules/blob/dev/Nuke.py#L8-L20)

**Comment by josh-cunning** [comment]
Sounds like a solid idea. I will create a casino file. Will make it similar to duel with .gamble <name of game>

**Comment by Berserkir-Wolf** [comment]
GITWIKIURL = "https://github.com/deathbybandaid/sopel-modules/wiki/Casino" ## Wiki url


For reference:
https://github.com/deathbybandaid/sopel-modules/blob/dev/Challenges.py#L32
https://github.com/deathbybandaid/sopel-modules/blob/dev/Challenges.py#L211-L213
https://github.com/deathbybandaid/sopel-modules/blob/dev/Challenges.py#L231-L241

**Comment by josh-cunning** [comment]
Okay so I remove the roulette and blackjack modules and put them in the casino.py file
Will work out some of bugs and document the usage

**Comment by josh-cunning** [comment]
Updated the documentation will check with PM before deleting the lottery module
